# Generated by Django 4.1.2 on 2024-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megagames', '0002_consola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
