# Generated by Django 4.1.2 on 2024-06-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megagames', '0003_alter_consola_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugete',
            fields=[
                ('idjugete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url_imagen', models.URLField(verbose_name='URL de la Imagen')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
