# Generated by Django 4.1.2 on 2024-06-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megagames', '0004_jugete'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='url_imagen',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
