# Generated by Django 4.1.2 on 2024-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megagames', '0005_videojuego_imagen_alter_videojuego_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='url_imagen',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
